# Generated by Django 5.0.7 on 2024-07-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_campaign_description_campaign_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
